export enum NatsServices {
  LOCATIONS = 'LOCATIONS_SERVICE',
  EVENTS = 'EVENTS_SERVICE',
  TICKETS = 'TICKETS_SERVICE',
  TICKET_SALES = 'TICKET_SALES_SERVICE',
  PAYMENTS = 'PAYMENTS_SERVICE',
  EMAIL = 'EMAIL_SERVICE',
  STORAGE = 'STORAGE_SERVICE',
}
